import { Router } from "express";
import { asyncHandler } from "../../utils/http.js";
import { assignLead, bulkPromoteLeadsToPipeline, changeLeadPriority, changeLeadStage, convertLead, createConsultation, createLead, createLeadFollowUp, getAgeingReport, getConversionTrendReport, getEmployeeReport, getFunnelReport, getLead, getLeadDashboard, getLeadDashboardDrilldown, getLeadSettings, getLostReport, getResponseTimeReport, getSourceReport, getWorkloadReport, listConsultations, listLeads, listLeadSources, listLeadStaff, markLeadLost, moveLeadToNurture, promoteLeadToPipeline, qualifyLead, reactivateLead, recordLeadActivity, updateCommercialStatus, updateConsultation, updateLeadDetails, updateLeadFollowUp, updateLeadSettings } from "./lead.controller.js";
import { commitImport, createForm, forceCreateFromEvent, getDuplicateReview, getImport, getOperations, listEvents, listForms, listImports, previewImport, resolveDuplicate, retryEvent, updateForm } from "./lead.intake.controller.js";
import { receiveLeadCsv } from "./lead.intake.upload.js";
import { createConnection, createSourceConnection, listConnections, listSourceConnections, rotateSecret, rotateSourceConnectionSecret, updateConnection, updateSourceConnection } from "./lead.website.controller.js";
import { requireRole } from "../../middleware/authorization.js";
import { createLeadLedgerEntry, deleteLedgerEntry, listImportReviewLedgerEntries, listLeadLedgerEntries, updateLedgerEntry } from "../../controllers/manualLedgerController.js";

const router = Router();

router.get("/sources", asyncHandler(listLeadSources));
router.get("/staff", asyncHandler(listLeadStaff));
router.get("/settings", asyncHandler(getLeadSettings));
router.patch("/settings", requireRole("admin"), asyncHandler(updateLeadSettings));
router.get("/dashboard", requireRole("admin"), asyncHandler(getLeadDashboard));
router.get("/dashboard/drilldown", requireRole("admin"), asyncHandler(getLeadDashboardDrilldown));
router.get("/reports/funnel", requireRole("admin"), asyncHandler(getFunnelReport));
router.get("/reports/sources", requireRole("admin"), asyncHandler(getSourceReport));
router.get("/reports/employees", requireRole("admin"), asyncHandler(getEmployeeReport));
router.get("/reports/lost", requireRole("admin"), asyncHandler(getLostReport));
router.get("/reports/response-time", requireRole("admin"), asyncHandler(getResponseTimeReport));
router.get("/reports/ageing", requireRole("admin"), asyncHandler(getAgeingReport));
router.get("/reports/trends", requireRole("admin"), asyncHandler(getConversionTrendReport));
router.get("/reports/workload", requireRole("admin"), asyncHandler(getWorkloadReport));
router.get("/intake/forms", asyncHandler(listForms));
router.post("/intake/forms", requireRole("admin"), asyncHandler(createForm));
router.patch("/intake/forms/:formId", requireRole("admin"), asyncHandler(updateForm));
router.get("/intake/events", requireRole("admin"), asyncHandler(listEvents));
router.get("/intake/operations", requireRole("admin"), asyncHandler(getOperations));
router.post("/intake/events/:eventId/retry", requireRole("admin"), asyncHandler(retryEvent));
router.get("/intake/events/:eventId/duplicates", requireRole("admin"), asyncHandler(getDuplicateReview));
router.post("/intake/events/:eventId/duplicates/:candidateId/resolve", requireRole("admin"), asyncHandler(resolveDuplicate));
router.post("/intake/events/:eventId/create-anyway", requireRole("admin"), asyncHandler(forceCreateFromEvent));
router.get("/intake/website-connections", requireRole("admin"), asyncHandler(listConnections));
router.post("/intake/website-connections", requireRole("admin"), asyncHandler(createConnection));
router.patch("/intake/website-connections/:connectionId", requireRole("admin"), asyncHandler(updateConnection));
router.post("/intake/website-connections/:connectionId/rotate-secret", requireRole("admin"), asyncHandler(rotateSecret));
router.get("/intake/connections", requireRole("admin"), asyncHandler(listSourceConnections));
router.post("/intake/connections", requireRole("admin"), asyncHandler(createSourceConnection));
router.patch("/intake/connections/:connectionId", requireRole("admin"), asyncHandler(updateSourceConnection));
router.post("/intake/connections/:connectionId/rotate-secret", requireRole("admin"), asyncHandler(rotateSourceConnectionSecret));
router.get("/imports", requireRole("admin", "consultant"), asyncHandler(listImports));
router.post("/imports/preview", requireRole("admin", "consultant"), receiveLeadCsv, asyncHandler(previewImport));
router.get("/imports/:batchId", requireRole("admin", "consultant"), asyncHandler(getImport));
router.post("/imports/:batchId/commit", requireRole("admin", "consultant"), asyncHandler(commitImport));
router.get("/", asyncHandler(listLeads));
router.post("/", asyncHandler(createLead));
router.post("/:id/activities", asyncHandler(recordLeadActivity));
router.post("/:id/follow-ups", asyncHandler(createLeadFollowUp));
router.patch("/:id/follow-ups/:followUpId", asyncHandler(updateLeadFollowUp));
router.post("/:id/assign", requireRole("admin"), asyncHandler(assignLead));
router.post("/:id/nurture", asyncHandler(moveLeadToNurture));
router.post("/:id/lost", asyncHandler(markLeadLost));
router.post("/:id/reactivate", asyncHandler(reactivateLead));
router.post("/:id/promote", asyncHandler(promoteLeadToPipeline));
router.post("/promote-bulk", asyncHandler(bulkPromoteLeadsToPipeline));
router.post("/:id/qualify", requireRole("admin", "consultant"), asyncHandler(qualifyLead));
router.patch("/:id/stage", requireRole("admin", "consultant"), asyncHandler(changeLeadStage));
router.patch("/:id/priority", requireRole("admin", "consultant"), asyncHandler(changeLeadPriority));
router.patch("/:id/commercial-status", requireRole("admin", "consultant"), asyncHandler(updateCommercialStatus));
router.post("/:id/convert", requireRole("admin", "consultant"), asyncHandler(convertLead));
router.get("/:id/consultations", asyncHandler(listConsultations));
router.post("/:id/consultations", asyncHandler(createConsultation));
router.patch("/:id/consultations/:consultationId", requireRole("admin", "consultant"), asyncHandler(updateConsultation));
router.get("/ledger/import-review", requireRole("admin"), asyncHandler(listImportReviewLedgerEntries));
router.get("/:leadId/ledger", asyncHandler(listLeadLedgerEntries));
router.post("/:leadId/ledger", asyncHandler(createLeadLedgerEntry));
router.patch("/:leadId/ledger/:entryId", asyncHandler(updateLedgerEntry));
router.delete("/:leadId/ledger/:entryId", asyncHandler(deleteLedgerEntry));
router.patch("/:id", asyncHandler(updateLeadDetails));
router.get("/:id", asyncHandler(getLead));

export default router;
