import { Router } from "express";
import { assignCatalogForms, checkCaseFormVersion, createCaseFormReviewComment, createCustomCaseForm, deleteCaseForm, deleteCaseFormReviewComment, finalizeCaseForm, getCaseFormCatalog, getCurrentFormPermissions, importOfficialCaseForm, listCaseFormAudit, listCaseFormReviewComments, listCaseForms, listCaseFormVersions, recordCaseFormAutofill, restoreCaseFormVersion, saveBrowserCaseFormCopy, serveCaseFormFile, serveCaseFormVersionFile, setCaseFormReviewCommentResolution, unlockCaseForm, updateCaseForm, updateUserFormPermissions, uploadCaseForm } from "../controllers/caseFormController.js";
import { receiveDocumentFile } from "../middleware/documentUploadMiddleware.js";
import { asyncHandler } from "../utils/http.js";

const router = Router();
router.get("/catalog", asyncHandler(getCaseFormCatalog));
router.get("/permissions", asyncHandler(getCurrentFormPermissions));
router.patch("/permissions/:userId", asyncHandler(updateUserFormPermissions));
router.get("/", asyncHandler(listCaseForms));
router.post("/assign", asyncHandler(assignCatalogForms));
router.post("/custom", receiveDocumentFile, asyncHandler(createCustomCaseForm));
router.post("/:id/upload", receiveDocumentFile, asyncHandler(uploadCaseForm));
router.post("/:id/copies", receiveDocumentFile, asyncHandler(saveBrowserCaseFormCopy));
router.post("/:id/import", asyncHandler(importOfficialCaseForm));
router.post("/:id/check-version", asyncHandler(checkCaseFormVersion));
router.post("/:id/finalize", asyncHandler(finalizeCaseForm));
router.post("/:id/unlock", asyncHandler(unlockCaseForm));
router.get("/:id/versions", asyncHandler(listCaseFormVersions));
router.get("/:id/versions/:versionId/file", asyncHandler(serveCaseFormVersionFile));
router.post("/:id/versions/:versionId/restore", asyncHandler(restoreCaseFormVersion));
router.get("/:id/review-comments", asyncHandler(listCaseFormReviewComments));
router.get("/:id/audit", asyncHandler(listCaseFormAudit));
router.post("/:id/audit/autofill", asyncHandler(recordCaseFormAutofill));
router.post("/:id/review-comments", asyncHandler(createCaseFormReviewComment));
router.patch("/:id/review-comments/:commentId", asyncHandler(setCaseFormReviewCommentResolution));
router.delete("/:id/review-comments/:commentId", asyncHandler(deleteCaseFormReviewComment));
router.get("/:id/file", asyncHandler(serveCaseFormFile));
router.patch("/:id", asyncHandler(updateCaseForm));
router.delete("/:id", asyncHandler(deleteCaseForm));
export default router;
