import { Router } from "express";
import { createPortalMessage, getPortalRealtimeConfig, markPortalChatRead, portalActions, portalApplications, portalAppointments, portalDocuments, portalMe, portalMessages, portalProfile, servePortalDocument, servePortalMessageAttachment, uploadPortalDocument, uploadPortalMessageAttachment } from "../controllers/portalController.js";
import { subscribeToPush, unsubscribeFromPush } from "../controllers/pushSubscriptionController.js";
import { receiveDocumentFile } from "../middleware/documentUploadMiddleware.js";
import { rateLimit } from "../middleware/rateLimit.js";
import { requireRole } from "../middleware/authorization.js";
import { asyncHandler } from "../utils/http.js";
const router = Router();
router.use(requireRole("client"));
router.get("/me", asyncHandler(portalMe));
router.post("/push/subscribe", rateLimit({ windowMs: 60_000, max: 10 }), asyncHandler(subscribeToPush));
router.post("/push/unsubscribe", rateLimit({ windowMs: 60_000, max: 10 }), asyncHandler(unsubscribeFromPush));
router.get("/applications", asyncHandler(portalApplications));
router.get("/documents", asyncHandler(portalDocuments));
router.post("/documents/:id/upload", rateLimit({ windowMs: 60_000, max: 10 }), receiveDocumentFile, asyncHandler(uploadPortalDocument));
router.get("/documents/:id/file", asyncHandler(servePortalDocument));
router.get("/appointments", asyncHandler(portalAppointments));
router.get("/actions", asyncHandler(portalActions));
router.get("/messages", asyncHandler(portalMessages));
router.get("/messages/realtime", asyncHandler(getPortalRealtimeConfig));
router.post("/messages", rateLimit({ windowMs: 60_000, max: 20 }), asyncHandler(createPortalMessage));
router.post("/messages/:id/attachments", rateLimit({ windowMs: 60_000, max: 10 }), receiveDocumentFile, asyncHandler(uploadPortalMessageAttachment));
router.get("/messages/:id/attachments/:attachmentId/file", asyncHandler(servePortalMessageAttachment));
router.post("/messages/read", asyncHandler(markPortalChatRead));
router.get("/profile", asyncHandler(portalProfile));
export default router;
