import { Router } from "express";
import { createPortalMessage, getPortalRealtimeConfig, markPortalChatRead, portalActions, portalApplications, portalAppointments, portalDocuments, portalMe, portalMessages, portalProfile, servePortalDocument, servePortalMessageAttachment, uploadPortalDocument, uploadPortalMessageAttachment } from "../controllers/portalController.js";
import { subscribeToPush, unsubscribeFromPush } from "../controllers/pushSubscriptionController.js";
import { receiveCompressedCaseDocument, receiveDocumentFile } from "../middleware/documentUploadMiddleware.js";
import { rateLimit } from "../middleware/rateLimit.js";
import { requireRole } from "../middleware/authorization.js";
import { asyncHandler } from "../utils/http.js";
import { requireClientPortalPermission as permit } from "../middleware/clientPortalPolicy.js";
const router = Router();
router.use(requireRole("client"));
router.get("/me", permit("general.access"), asyncHandler(portalMe));
router.post("/push/subscribe", rateLimit({ windowMs: 60_000, max: 10 }), asyncHandler(subscribeToPush));
router.post("/push/unsubscribe", rateLimit({ windowMs: 60_000, max: 10 }), asyncHandler(unsubscribeFromPush));
router.get("/applications", permit("case_information.view", { resource: "allCases" }), asyncHandler(portalApplications));
router.get("/documents", permit("documents.view"), asyncHandler(portalDocuments));
router.post("/documents/:id/upload", permit("documents.upload", { resource: "document" }), rateLimit({ windowMs: 60_000, max: 10 }), receiveCompressedCaseDocument, asyncHandler(uploadPortalDocument));
router.get("/documents/:id/file", permit("documents.download_finalized", { resource: "document" }), asyncHandler(servePortalDocument));
router.get("/appointments", permit("appointments.view", { resource: "allCases" }), asyncHandler(portalAppointments));
router.get("/actions", permit("dashboard.view_next_action"), asyncHandler(portalActions));
router.get("/messages", permit("communication.view_history", { resource: "allCases" }), asyncHandler(portalMessages));
router.get("/messages/realtime", permit("communication.view_history"), asyncHandler(getPortalRealtimeConfig));
router.post("/messages", permit("communication.create_conversation"), rateLimit({ windowMs: 60_000, max: 20 }), asyncHandler(createPortalMessage));
router.post("/messages/:id/attachments", permit("communication.upload_attachments", { resource: "conversation" }), rateLimit({ windowMs: 60_000, max: 10 }), receiveDocumentFile, asyncHandler(uploadPortalMessageAttachment));
router.get("/messages/:id/attachments/:attachmentId/file", permit("communication.view_history", { resource: "conversation" }), asyncHandler(servePortalMessageAttachment));
router.post("/messages/read", permit("communication.view_history"), asyncHandler(markPortalChatRead));
router.get("/profile", permit("case_information.view", { resource: "allCases" }), asyncHandler(portalProfile));
export default router;
