import { Router } from "express";
import { createPortalMessage, portalActions, portalApplications, portalAppointments, portalDocuments, portalMe, portalMessages, portalProfile, servePortalDocument, uploadPortalDocument } from "../controllers/portalController.js";
import { receiveDocumentFile } from "../middleware/documentUploadMiddleware.js";
import { rateLimit } from "../middleware/rateLimit.js";
import { requireRole } from "../middleware/authorization.js";
import { asyncHandler } from "../utils/http.js";
const router = Router();
router.use(requireRole("client"));
router.get("/me", asyncHandler(portalMe));
router.get("/applications", asyncHandler(portalApplications));
router.get("/documents", asyncHandler(portalDocuments));
router.post("/documents/:id/upload", rateLimit({ windowMs: 60_000, max: 10 }), receiveDocumentFile, asyncHandler(uploadPortalDocument));
router.get("/documents/:id/file", asyncHandler(servePortalDocument));
router.get("/appointments", asyncHandler(portalAppointments));
router.get("/actions", asyncHandler(portalActions));
router.get("/messages", asyncHandler(portalMessages));
router.post("/messages", rateLimit({ windowMs: 60_000, max: 20 }), asyncHandler(createPortalMessage));
router.get("/profile", asyncHandler(portalProfile));
export default router;
