import { CheckCircle2, FileText, Plus, Save, X } from "lucide-react";
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { motion } from "framer-motion";

const yesNo = ["", "Yes", "No"];
const inputClass = "mt-2 w-full rounded-2xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none transition focus:border-slate-400";

export const profileQuestionnaireSections = {
  applicantIdentity: { title: "Applicant Identity", description: "Structured biographical details used across official immigration forms. Enter names exactly as shown on the passport or travel document.", fields: [["familyName", "Family name", "text"], ["givenNames", "Given name(s)", "text"], ["gender", "Gender", "select", ["", "Female", "Male", "Non-binary", "Another gender", "Prefer not to say"]], ["cityOfBirth", "City or town of birth"], ["countryOfBirth", "Country of birth"], ["citizenships", "Citizenship(s)"], ["nativeLanguage", "Native language / mother tongue"], ["preferredLanguage", "Language most at ease in", "select", ["", "English", "French", "Both", "Neither"]]] },
  canadianStatus: { title: "Canadian Status", description: "Current or previous Canadian immigration status and application history.", fields: [["currentlyInCanada", "Are you currently in Canada?", "select", yesNo], ["currentStatus", "Current immigration status in Canada"], ["statusExpiry", "Current status expiry date", "date"], ["uci", "Unique Client Identifier (UCI)"], ["priorCanadaApplication", "Have you previously applied to enter or remain in Canada?", "select", yesNo], ["refusedCanadaApplication", "Have you ever been refused a visa, permit, or other application?", "select", yesNo], ["refusalDetails", "If yes, provide refusal details", "textarea", null, "refusedCanadaApplication"]] },
  background: { title: "Background & Admissibility", description: "Declarations used across temporary, permanent, refugee, and citizenship applications.", fields: [["medicalCondition", "Do you have a medical condition that may require an immigration medical exam?", "select", yesNo], ["medicalDetails", "Provide relevant medical details", "textarea", null, "medicalCondition"], ["criminalHistory", "Have you been arrested, detained, charged, or convicted of an offence in any country?", "select", yesNo], ["criminalDetails", "Provide the date, location, charge, outcome, and sentence", "textarea", null, "criminalHistory"], ["immigrationViolation", "Have you overstayed, worked, or studied without authorization?", "select", yesNo], ["violationDetails", "Provide immigration-violation details", "textarea", null, "immigrationViolation"], ["visaRefusal", "Have you been refused a visa or permit, denied entry, or ordered to leave any country?", "select", yesNo], ["visaRefusalDetails", "Provide refusal, denial, removal, or deportation details", "textarea", null, "visaRefusal"], ["militaryService", "Have you served in the military, militia, civil defence, security, or police?", "select", yesNo], ["militaryDetails", "Provide organization, rank, location, and dates of service", "textarea", null, "militaryService"], ["governmentPosition", "Have you held a government, judicial, or political position?", "select", yesNo], ["governmentDetails", "Provide position, organization, country, and dates", "textarea", null, "governmentPosition"], ["securityConcern", "Have you participated in an organization or activity involving violence, human-rights violations, or security concerns?", "select", yesNo], ["securityDetails", "Provide full details", "textarea", null, "securityConcern"]] },
  sponsorship: { title: "Relationship & Sponsorship", description: "Sponsor eligibility and relationship evidence for family-class applications.", fields: [["sponsorStatus", "Sponsor's status in Canada"], ["relationshipType", "Relationship to the person being sponsored"], ["relationshipStartDate", "Date the relationship began", "date"], ["cohabitationStartDate", "Date cohabitation began, if applicable", "date"], ["marriageDate", "Date of marriage, if applicable", "date"], ["relationshipEvidence", "Describe available relationship evidence", "textarea"], ["sponsorFinancialSupport", "Will the sponsor provide financial support?", "select", yesNo]] },
  programDetails: { title: "Purpose, Funds & Program Details", description: "Program-specific information used to tailor temporary and permanent-residence questionnaires.", fields: [["purposeOfTravel", "Explain the purpose of travel or intended activity in Canada", "textarea"], ["plannedArrivalDate", "Planned arrival date", "date"], ["plannedDepartureDate", "Planned departure date, if temporary", "date"], ["intendedLengthOfStay", "Intended length of stay"], ["destination", "Destination city and province"], ["accommodation", "Where will you stay in Canada?", "textarea"], ["invitingPerson", "Inviting person or organization in Canada, if applicable", "textarea"], ["fundsAvailable", "Total funds available for the application and stay"], ["fundsCurrency", "Currency of available funds"], ["fundingSource", "Source of funds"], ["tripPayer", "Who will pay for travel, tuition, and living expenses?"], ["financialEvidence", "What financial evidence is available?", "textarea"], ["homeCountryTies", "Describe employment, family, property, or other ties supporting your return", "textarea"], ["returnPlan", "Describe your plan after the authorized stay ends", "textarea"], ["canadianEmployer", "Canadian employer or job offer details, if applicable", "textarea"], ["educationalInstitution", "Canadian educational institution, program, and DLI details, if applicable", "textarea"], ["provincialNomination", "Do you have a provincial nomination?", "select", yesNo], ["nominationDetails", "Provide province, stream, certificate number, and expiry", "textarea", null, "provincialNomination"], ["businessProposal", "Business or start-up proposal details, if applicable", "textarea"]] },
  humanitarianCitizenship: { title: "Humanitarian, Citizenship & Establishment", description: "Humanitarian circumstances, physical presence, taxes, and citizenship prohibitions.", fields: [["canadianEstablishment", "Describe your establishment in Canada (work, education, community, family)", "textarea"], ["hardshipDetails", "Describe hardship if required to leave Canada", "textarea"], ["childrenBestInterest", "Describe the best interests of any affected children", "textarea"], ["physicalPresenceDays", "Physical-presence days in Canada, if applying for citizenship", "number"], ["taxFiledYears", "Tax years filed in Canada, if applicable"], ["citizenshipProhibition", "Are you subject to a citizenship prohibition?", "select", yesNo], ["prohibitionDetails", "If yes, provide details", "textarea", null, "citizenshipProhibition"]] },
  rehabilitation: { title: "Rehabilitation & Court Details", description: "Criminal rehabilitation information, including offences, court outcomes, and rehabilitation evidence.", fields: [["offenceDate", "Date of offence", "date"], ["offenceCountry", "Country or territory where the offence occurred"], ["offenceDescription", "Offence and charge description", "textarea"], ["courtOutcome", "Court outcome and sentence", "textarea"], ["sentenceCompletedDate", "Date sentence was completed", "date"], ["policeCertificates", "Police certificates available", "textarea"], ["rehabilitationEvidence", "Describe rehabilitation and reasons the application should be approved", "textarea"]] },
  refugeeProtection: { title: "Refugee Claim & Protection", description: "Claim narrative, risks, protection history, and supporting evidence for refugee applications.", fields: [["claimBasis", "Describe the basis of the refugee or protection claim", "textarea"], ["fearedPersons", "Who or what do you fear in your country of nationality or residence?", "textarea"], ["riskEvents", "Describe threats, harm, persecution, or serious risks experienced", "textarea"], ["policeProtection", "Did you seek protection from police or other authorities?", "select", yesNo], ["policeProtectionDetails", "Explain the protection sought and the outcome", "textarea", null, "policeProtection"], ["internalRelocation", "Could you safely relocate to another part of the country?", "select", yesNo], ["internalRelocationDetails", "Explain why relocation is or is not possible", "textarea"], ["priorClaims", "Have you made a refugee or asylum claim in another country?", "select", yesNo], ["priorClaimDetails", "Provide details of prior claims", "textarea", null, "priorClaims"], ["supportingEvidence", "List available supporting evidence", "textarea"]] },
};

export default function ProfileQuestionnaireSection({ sectionId, initialData, saving, error, onSave }) {
  const config = profileQuestionnaireSections[sectionId];
  const [values, setValues] = useState(initialData || {});
  const [editing, setEditing] = useState(false);
  useEffect(() => { setValues(initialData || {}); }, [initialData, sectionId]);
  if (!config) return null;
  const update = (key, value) => setValues((current) => ({ ...current, [key]: value }));
  const hasData = Object.values(initialData || {}).some((value) => String(value || "").trim());
  const overlay = editing && typeof document !== "undefined" ? createPortal(<div className="fixed inset-0 z-[290] bg-slate-950/24 p-3 backdrop-blur-md"><motion.form initial={{ opacity: 0, y: 16, scale: 0.985 }} animate={{ opacity: 1, y: 0, scale: 1 }} onSubmit={async (event) => { event.preventDefault(); await onSave(values); setEditing(false); }} className="mx-auto flex h-full max-w-5xl flex-col overflow-hidden rounded-[2rem] border border-white/80 bg-white shadow-[0_28px_80px_rgba(15,23,42,0.26)]"><header className="flex items-start justify-between gap-4 border-b border-slate-100 px-5 py-4"><div><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-400">Client Information Form</p><h2 className="mt-1 text-xl font-semibold text-slate-950">{config.title}</h2><p className="mt-1 max-w-3xl text-sm text-slate-500">{config.description}</p></div><button type="button" onClick={() => setEditing(false)} disabled={saving} className="flex h-10 w-10 items-center justify-center rounded-full border border-slate-200"><X className="h-4 w-4" /></button></header><main className="min-h-0 flex-1 overflow-y-auto bg-slate-50/60 px-5 py-5">{error ? <div className="mb-4 rounded-2xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div> : null}<section className="rounded-[1.5rem] border border-slate-100 bg-white p-4"><div className="grid gap-4 md:grid-cols-2">{config.fields.map(([key, label, type = "text", options, showWhen]) => { if (showWhen && values[showWhen] !== "Yes") return null; return <label key={key} className={`block ${type === "textarea" ? "md:col-span-2" : ""}`}><span className="block text-sm font-semibold leading-5 text-slate-800">{label}</span>{type === "select" ? <select value={values[key] || ""} onChange={(event) => update(key, event.target.value)} className={inputClass}>{options.map((option) => <option key={option || "empty"} value={option}>{option || "Select"}</option>)}</select> : type === "textarea" ? <textarea rows={4} value={values[key] || ""} onChange={(event) => update(key, event.target.value)} className={inputClass} /> : <input type={type} value={values[key] || ""} onChange={(event) => update(key, event.target.value)} className={inputClass} />}</label>; })}</div></section></main><footer className="flex items-center justify-between gap-3 border-t border-slate-100 px-5 py-4"><span className="inline-flex items-center gap-2 text-xs text-slate-500"><FileText className="h-4 w-4" />Partial details can be saved.</span><div className="flex gap-2"><button type="button" onClick={() => setEditing(false)} disabled={saving} className="rounded-full border border-slate-200 px-4 py-2.5 text-sm font-semibold">Cancel</button><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-full bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><Save className="h-4 w-4" />{saving ? "Saving" : "Save details"}</button></div></footer></motion.form></div>, document.body) : null;
  return <div className="space-y-4"><section className="rounded-[1.35rem] bg-[linear-gradient(135deg,#f8fafc,#eef2f7)] px-4 py-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-400">Client Information Form</p><h4 className="mt-2 text-lg font-semibold tracking-tight text-slate-950">{config.title}</h4><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{config.description}</p></div>{hasData ? <button type="button" onClick={() => setEditing(true)} className="inline-flex w-fit shrink-0 rounded-full bg-slate-950 px-3 py-1.5 text-xs font-semibold text-white">Edit Details</button> : null}</div></section>{hasData ? <section className="rounded-[1.35rem] bg-slate-50 p-4"><div className="grid gap-3 md:grid-cols-2">{config.fields.filter(([,, , , showWhen]) => !showWhen || values[showWhen] === "Yes").map(([key, label]) => <div key={key} className="rounded-xl bg-white px-3 py-3 ring-1 ring-slate-100"><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-slate-900">{values[key] || "Not set"}</p></div>)}</div><p className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-slate-500"><CheckCircle2 className="h-4 w-4 text-emerald-600" />Details saved to the client profile.</p></section> : <div className="flex min-h-[220px] items-center justify-center rounded-[1.35rem] bg-slate-50 px-5 py-8 text-center"><div><div className="mx-auto flex h-10 w-10 items-center justify-center rounded-full bg-white text-slate-500 shadow-sm"><Plus className="h-4 w-4" /></div><h4 className="mt-3 text-sm font-semibold text-slate-950">No details added yet</h4><p className="mx-auto mt-2 max-w-md text-sm text-slate-500">Add the information when it is relevant to the selected application.</p><button type="button" onClick={() => setEditing(true)} className="mt-4 inline-flex items-center justify-center rounded-full bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Add Details</button></div></div>}{overlay}</div>;
}
