import { AlertTriangle, ArrowRight, BarChart3, CalendarClock, CheckCircle2, ContactRound, Gauge, Hourglass, Megaphone, RotateCcw, Timer, TrendingDown, UsersRound, WalletCards } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import api from "../../../services/api";
import { humanize } from "../leadPresentation";

const ranges = [{ value: "7", label: "Last 7 days" }, { value: "30", label: "Last 30 days" }, { value: "90", label: "Last 90 days" }, { value: "365", label: "Last year" }, { value: "all", label: "All time" }];

function ReportSkeleton() {
  return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3">{Array.from({ length: 3 }).map((_, index) => <div key={index} className="h-28 animate-pulse rounded-2xl bg-slate-100" />)}</div><div className="h-[560px] animate-pulse rounded-3xl bg-slate-100" /></div>;
}

function SummaryCard({ icon: Icon, label, value, tone = "brand" }) {
  const toneClass = { brand: "text-brand-600", emerald: "text-emerald-600", violet: "text-violet-600" }[tone];
  return <article className="rounded-2xl border border-slate-200/70 bg-white p-5"><div className="flex items-center gap-2 text-sm font-medium text-slate-500"><Icon className={`h-4 w-4 ${toneClass}`} />{label}</div><p className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-slate-950">{value}</p></article>;
}

function FunnelReport({ report }) {
  const received = report.funnel[0]?.count || 0;
  const converted = report.funnel.at(-1)?.count || 0;
  return <>
    <section className="grid gap-3 sm:grid-cols-3"><SummaryCard icon={ContactRound} label="Valid leads received" value={received} /><SummaryCard icon={CheckCircle2} label="Converted clients" value={converted} tone="emerald" /><SummaryCard icon={BarChart3} label="Overall conversion" value={`${report.overallConversionRate}%`} tone="violet" /></section>
    <section className="overflow-hidden rounded-3xl border border-white/80 bg-white shadow-[0_18px_55px_rgba(28,45,74,0.08)]">
      <div className="border-b border-slate-200/70 px-5 py-4"><h2 className="text-base font-semibold text-slate-950">Conversion funnel</h2><p className="mt-1 text-xs text-slate-500">Each percentage is measured against valid leads received in the selected period.</p></div>
      <div className="divide-y divide-slate-100">{report.funnel.map((item, index) => <div key={item.step} className="grid gap-3 px-5 py-4 md:grid-cols-[210px_minmax(240px,1fr)_90px_150px] md:items-center"><div><p className="text-sm font-semibold text-slate-800">{humanize(item.step)}</p><p className="mt-0.5 text-xs text-slate-400">Step {index + 1} of {report.funnel.length}</p></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${item.step === "CONVERTED" ? "bg-emerald-500" : "bg-brand-500"}`} style={{ width: `${Math.max(item.shareOfReceived, item.count ? 2 : 0)}%` }} /></div><div className="text-left md:text-right"><span className="text-lg font-semibold text-slate-900">{item.count}</span><span className="ml-1 text-xs text-slate-400">{item.shareOfReceived}%</span></div><div>{index ? <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${item.dropOffFromPrevious ? "bg-rose-50 text-rose-700" : "bg-emerald-50 text-emerald-700"}`}><TrendingDown className="h-3.5 w-3.5" />{item.dropOffFromPrevious} drop-off</span> : <span className="text-xs text-slate-400">Starting population</span>}</div></div>)}</div>
    </section>
    <Definition>The period is based on when the lead was received. Duplicate and archived records are excluded. Funnel milestones use contact timestamps, qualification history, consultation records, stage history, and completed conversions.</Definition>
  </>;
}

function formatResponse(minutes) {
  if (minutes === null || minutes === undefined) return "—";
  if (minutes < 60) return `${Math.round(minutes)}m`;
  return `${Math.floor(minutes / 60)}h ${Math.round(minutes % 60)}m`;
}

function SourceReport({ report }) {
  const money = new Intl.NumberFormat("en-CA", { style: "currency", currency: report.currency || "CAD", maximumFractionDigits: 0 });
  const best = [...report.sources].filter((source) => source.leadsReceived).sort((left, right) => right.conversionRate - left.conversionRate)[0];
  return <>
    <section className="grid gap-3 sm:grid-cols-3"><SummaryCard icon={Megaphone} label="Sources producing leads" value={report.summary.sourcesWithLeads} /><SummaryCard icon={ContactRound} label="Leads received" value={report.summary.leadsReceived} /><SummaryCard icon={CheckCircle2} label="Best conversion source" value={best ? `${best.name} · ${best.conversionRate}%` : "—"} tone="emerald" /></section>
    <section className="overflow-hidden rounded-3xl border border-white/80 bg-white shadow-[0_18px_55px_rgba(28,45,74,0.08)]">
      <div className="border-b border-slate-200/70 px-5 py-4"><h2 className="text-base font-semibold text-slate-950">Source performance</h2><p className="mt-1 text-xs text-slate-500">Volume, progression, response speed, and financial outcome by original source.</p></div>
      {!report.sources.length ? <div className="px-6 py-16 text-center"><p className="text-sm font-semibold text-slate-800">No source activity in this period</p><p className="mt-1 text-xs text-slate-500">Choose a wider date range to review earlier leads.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[1160px] text-left"><thead><tr className="border-b border-slate-200 bg-slate-50/70 text-[10px] font-semibold uppercase tracking-[0.07em] text-slate-500"><th className="px-5 py-3">Source</th><th className="px-3 py-3">Received</th><th className="px-3 py-3">Contacted</th><th className="px-3 py-3">Qualified</th><th className="px-3 py-3">Consultations</th><th className="px-3 py-3">Converted</th><th className="px-3 py-3">Lost</th><th className="px-3 py-3">Conversion</th><th className="px-3 py-3">Avg response</th><th className="px-3 py-3">Pipeline</th><th className="px-3 py-3">Converted value</th><th className="px-5 py-3">Main lost reason</th></tr></thead><tbody>{report.sources.map((source) => <tr key={source.id} className="border-b border-slate-100 text-sm last:border-0"><td className="px-5 py-4"><p className="font-semibold text-slate-900">{source.name}</p><p className="mt-0.5 text-xs text-slate-400">{humanize(source.type)}</p></td><td className="px-3 py-4 font-semibold text-slate-800">{source.leadsReceived}</td><td className="px-3 py-4 text-slate-600">{source.contacted}</td><td className="px-3 py-4 text-slate-600">{source.qualified}</td><td className="px-3 py-4 text-slate-600">{source.consultations}</td><td className="px-3 py-4 font-semibold text-emerald-700">{source.converted}</td><td className="px-3 py-4 text-rose-600">{source.lost}</td><td className="px-3 py-4"><span className="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-semibold text-brand-700">{source.conversionRate}%</span></td><td className="px-3 py-4"><span className="inline-flex items-center gap-1.5 text-slate-600"><Timer className="h-3.5 w-3.5 text-slate-400" />{formatResponse(source.averageResponseMinutes)}</span></td><td className="px-3 py-4 text-slate-600">{money.format(source.pipelineValue)}</td><td className="px-3 py-4 font-medium text-slate-700">{money.format(source.convertedValue)}</td><td className="px-5 py-4 text-xs text-slate-500">{source.mainLostReason ? humanize(source.mainLostReason) : "—"}</td></tr>)}</tbody></table></div>}
    </section>
    <Definition>Original source receives credit for the lead. Pipeline value includes open leads; converted value uses the recorded actual conversion value. Average response measures the first contact attempt from lead creation.</Definition>
  </>;
}

function EmployeeReport({ report }) {
  const money = new Intl.NumberFormat("en-CA", { style: "currency", currency: report.currency || "CAD", maximumFractionDigits: 0 });
  return <>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SummaryCard icon={UsersRound} label="Active employees" value={report.summary.employees} /><SummaryCard icon={ContactRound} label="Leads assigned" value={report.summary.leadsAssigned} /><SummaryCard icon={CheckCircle2} label="Converted" value={report.summary.converted} tone="emerald" /><SummaryCard icon={BarChart3} label="Converted revenue" value={money.format(report.summary.convertedRevenue)} tone="violet" /></section>
    <section className="overflow-hidden rounded-3xl border border-white/80 bg-white shadow-[0_18px_55px_rgba(28,45,74,0.08)]">
      <div className="border-b border-slate-200/70 px-5 py-4"><h2 className="text-base font-semibold text-slate-950">Employee performance</h2><p className="mt-1 text-xs text-slate-500">Work completed and outcomes for leads received in the selected period.</p></div>
      {!report.employees.length ? <div className="px-6 py-16 text-center"><p className="text-sm font-semibold text-slate-800">No employee activity in this period</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left"><thead><tr className="border-b border-slate-200 bg-slate-50/70 text-[10px] font-semibold uppercase tracking-[0.07em] text-slate-500"><th className="px-5 py-3">Employee</th><th className="px-4 py-3">Leads</th><th className="px-4 py-3">Contact activity</th><th className="px-4 py-3">Follow-ups</th><th className="px-4 py-3">Consultations</th><th className="px-4 py-3">Outcome</th><th className="px-4 py-3">Speed</th><th className="px-5 py-3">Revenue</th></tr></thead><tbody>{report.employees.map((employee) => <tr key={employee.id} className="border-b border-slate-100 align-top text-sm last:border-0"><td className="px-5 py-4"><p className="font-semibold text-slate-900">{employee.name}</p><p className="mt-0.5 text-xs text-slate-400">{employee.email}</p></td><td className="px-4 py-4"><p className="font-semibold text-slate-800">{employee.leadsAssigned} assigned</p><p className="mt-1 text-xs text-slate-400">{employee.newLeadsHandled} handled</p></td><td className="px-4 py-4"><p className="text-slate-700">{employee.contactAttempts} attempts · {employee.callsCompleted} calls</p><p className="mt-1 text-xs text-slate-400">{employee.successfulConnections} connected · {employee.noAnswerCalls} no answer</p></td><td className="px-4 py-4"><p className="text-slate-700">{employee.followUpsCompleted}/{employee.followUpsDue} completed</p><p className={`mt-1 text-xs ${employee.followUpsOverdue ? "font-semibold text-rose-600" : "text-slate-400"}`}>{employee.followUpsOverdue} overdue · {employee.followUpCompletionRate}%</p></td><td className="px-4 py-4"><p className="text-slate-700">{employee.consultationsCompleted}/{employee.consultationsBooked} completed</p></td><td className="px-4 py-4"><p className="font-semibold text-emerald-700">{employee.converted} converted</p><p className="mt-1 text-xs text-slate-400">{employee.lost} lost · {employee.conversionRate}%</p></td><td className="px-4 py-4"><p className="inline-flex items-center gap-1.5 text-slate-700"><Timer className="h-3.5 w-3.5 text-slate-400" />{formatResponse(employee.averageResponseMinutes)} response</p><p className="mt-1 text-xs text-slate-400">{formatResponse(employee.averageConnectionMinutes)} to connect</p></td><td className="px-5 py-4 font-semibold text-slate-800">{money.format(employee.convertedRevenue)}</td></tr>)}</tbody></table></div>}
    </section>
    <Definition>Leads are attributed to their owner. Contact activity is attributed to the employee who performed it; consultations and follow-ups use their assigned employee. Revenue uses actual conversion value.</Definition>
  </>;
}

function RankedList({ title, description, items, renderMeta }) {
  return <section className="overflow-hidden rounded-2xl border border-slate-200/70 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h3 className="text-sm font-semibold text-slate-900">{title}</h3><p className="mt-1 text-xs text-slate-500">{description}</p></div>{items.length ? <div>{items.map((item, index) => <div key={item.id || item.reason} className={`flex items-center justify-between gap-4 px-5 py-3.5 ${index ? "border-t border-slate-100" : ""}`}><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-700">{item.name || humanize(item.reason)}</p>{renderMeta ? <p className="mt-0.5 text-xs text-slate-400">{renderMeta(item)}</p> : null}</div><span className="shrink-0 rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{item.count}</span></div>)}</div> : <div className="px-5 py-8 text-center text-sm text-slate-400">No lost leads in this period.</div>}</section>;
}

function LostReport({ report }) {
  const largestReason = report.reasons[0]?.count || 1;
  return <>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SummaryCard icon={AlertTriangle} label="Lost leads" value={report.summary.totalLost} /><SummaryCard icon={ContactRound} label="No response" value={report.summary.noResponse} /><SummaryCard icon={RotateCcw} label="Reactivation opportunities" value={report.summary.reactivationOpportunities} tone="emerald" /><SummaryCard icon={UsersRound} label="Lost after consultation" value={report.summary.lostAfterConsultation} tone="violet" /></section>
    <section className="overflow-hidden rounded-3xl border border-white/80 bg-white shadow-[0_18px_55px_rgba(28,45,74,0.08)]"><div className="border-b border-slate-200/70 px-5 py-4"><h2 className="text-base font-semibold text-slate-950">Lost-reason breakdown</h2><p className="mt-1 text-xs text-slate-500">Why leads were closed as lost in the selected period.</p></div>{report.reasons.length ? <div className="divide-y divide-slate-100">{report.reasons.map((item) => <div key={item.reason} className="grid gap-3 px-5 py-4 sm:grid-cols-[220px_1fr_90px] sm:items-center"><p className="text-sm font-semibold text-slate-800">{humanize(item.reason)}</p><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-rose-400" style={{ width: `${Math.max((item.count / largestReason) * 100, 3)}%` }} /></div><p className="text-sm font-semibold text-slate-800 sm:text-right">{item.count} <span className="text-xs font-normal text-slate-400">· {item.share}%</span></p></div>)}</div> : <div className="px-6 py-16 text-center text-sm text-slate-400">No lost leads in this period.</div>}</section>
    <section className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200/70 bg-white px-5 py-4"><p className="text-xs font-medium text-slate-400">After consultation</p><p className="mt-2 text-2xl font-semibold text-slate-900">{report.summary.lostAfterConsultation}</p></div><div className="rounded-2xl border border-slate-200/70 bg-white px-5 py-4"><p className="text-xs font-medium text-slate-400">After agreement stage</p><p className="mt-2 text-2xl font-semibold text-slate-900">{report.summary.lostAfterAgreement}</p></div><div className="rounded-2xl border border-slate-200/70 bg-white px-5 py-4"><p className="text-xs font-medium text-slate-400">After payment stage</p><p className="mt-2 text-2xl font-semibold text-slate-900">{report.summary.lostAfterPayment}</p></div></section>
    <section className="grid gap-4 lg:grid-cols-2"><RankedList title="Lost by employee" description="Based on the lead owner at closure." items={report.employees} /><RankedList title="Lost by source" description="Based on the original lead source." items={report.sources} renderMeta={(item) => humanize(item.type)} /></section>
    <Definition>Lost reasons come from the required lost-detail record. Consultation, agreement, and payment-stage categories are diagnostic and may overlap when a lead reached multiple milestones. Reactivation opportunities require the reactivation flag.</Definition>
  </>;
}

function ResponseTimeReport({ report }) {
  const employeeItems = report.employees.map((item) => ({ ...item, count: item.late }));
  const sourceItems = report.sources.map((item) => ({ ...item, count: item.late }));
  return <>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SummaryCard icon={Timer} label="Average first attempt" value={formatResponse(report.summary.averageFirstAttemptMinutes)} /><SummaryCard icon={ContactRound} label="Average connection" value={formatResponse(report.summary.averageConnectionMinutes)} /><SummaryCard icon={Gauge} label="SLA compliance" value={`${report.summary.slaCompliance}%`} tone="emerald" /><SummaryCard icon={AlertTriangle} label="Never contacted" value={report.summary.neverContacted} tone="violet" /></section>
    <section className="rounded-3xl border border-white/80 bg-white p-5 shadow-[0_18px_55px_rgba(28,45,74,0.08)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-base font-semibold text-slate-950">First-response SLA</h2><p className="mt-1 text-xs text-slate-500">Completed responses and deadlines that have already passed.</p></div><p className="text-sm text-slate-500"><span className="font-semibold text-emerald-700">{report.summary.onTime} on time</span> · <span className="font-semibold text-rose-600">{report.summary.late} late</span> · {report.summary.evaluated} evaluated</p></div><div className="mt-5 flex h-3 overflow-hidden rounded-full bg-slate-100">{report.summary.evaluated ? <><div className="bg-emerald-500" style={{ width: `${(report.summary.onTime / report.summary.evaluated) * 100}%` }} /><div className="bg-rose-400" style={{ width: `${(report.summary.late / report.summary.evaluated) * 100}%` }} /></> : null}</div></section>
    <section className="grid gap-4 lg:grid-cols-2"><RankedList title="Late by employee" description="Employees with missed first-response deadlines." items={employeeItems} renderMeta={(item) => `${item.slaCompliance}% compliant · ${formatResponse(item.averageResponseMinutes)} average`} /><RankedList title="Late by source" description="Sources producing leads that missed response targets." items={sourceItems} renderMeta={(item) => `${item.slaCompliance}% compliant · ${formatResponse(item.averageResponseMinutes)} average`} /></section>
    <Definition>First response is the first recorded contact attempt minus lead creation time. Connection time uses the first successful connection. SLA compliance is on-time responses divided by evaluated deadlines; unresolved future deadlines are not yet evaluated.</Definition>
  </>;
}

const ageBucketLabels = { "0_1_DAYS": "0–1 days", "2_3_DAYS": "2–3 days", "4_7_DAYS": "4–7 days", "8_14_DAYS": "8–14 days", "15_30_DAYS": "15–30 days", "31_PLUS_DAYS": "31+ days" };

function AgeingReport({ report }) {
  const money = new Intl.NumberFormat("en-CA", { style: "currency", currency: report.currency || "CAD", maximumFractionDigits: 0 });
  const largestBucket = Math.max(...report.buckets.map((item) => item.count), 1);
  return <>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SummaryCard icon={ContactRound} label="Open leads" value={report.summary.totalOpen} /><SummaryCard icon={Hourglass} label="Average age" value={`${report.summary.averageAgeDays ?? 0} days`} /><SummaryCard icon={AlertTriangle} label={`Inactive ${report.inactiveThresholdDays}+ days`} value={report.summary.inactive} tone="violet" /><SummaryCard icon={BarChart3} label="Open pipeline" value={money.format(report.summary.pipelineValue)} tone="emerald" /></section>
    <section className="overflow-hidden rounded-3xl border border-white/80 bg-white shadow-[0_18px_55px_rgba(28,45,74,0.08)]"><div className="border-b border-slate-200/70 px-5 py-4"><h2 className="text-base font-semibold text-slate-950">Age distribution</h2><p className="mt-1 text-xs text-slate-500">Current open leads grouped by time since they were received.</p></div><div className="divide-y divide-slate-100">{report.buckets.map((item) => <div key={item.bucket} className="grid gap-3 px-5 py-4 sm:grid-cols-[150px_1fr_90px_150px] sm:items-center"><p className="text-sm font-semibold text-slate-800">{ageBucketLabels[item.bucket]}</p><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${item.bucket === "31_PLUS_DAYS" ? "bg-rose-400" : "bg-brand-500"}`} style={{ width: `${item.count ? Math.max((item.count / largestBucket) * 100, 3) : 0}%` }} /></div><p className="text-sm font-semibold text-slate-800 sm:text-right">{item.count} leads</p><p className="text-xs text-slate-500 sm:text-right">{money.format(item.pipelineValue)}</p></div>)}</div></section>
    <section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,2fr)]"><RankedList title="Open leads by stage" description="Count and average age in each current stage." items={report.stages.map((item) => ({ id: item.stage, name: humanize(item.stage), count: item.count, averageAgeDays: item.averageAgeDays }))} renderMeta={(item) => `${item.averageAgeDays ?? 0} days average`} /><section className="overflow-hidden rounded-2xl border border-slate-200/70 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h3 className="text-sm font-semibold text-slate-900">Oldest open leads</h3><p className="mt-1 text-xs text-slate-500">The oldest 25 records in the current pipeline.</p></div>{report.oldestLeads.length ? <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-slate-100 bg-slate-50/60 text-[10px] font-semibold uppercase tracking-[0.07em] text-slate-500"><th className="px-5 py-3">Lead</th><th className="px-3 py-3">Stage</th><th className="px-3 py-3">Owner</th><th className="px-3 py-3">Age</th><th className="px-3 py-3">Inactive</th><th className="px-5 py-3" /></tr></thead><tbody>{report.oldestLeads.map((lead) => <tr key={lead.id} className="border-b border-slate-100 text-sm last:border-0"><td className="px-5 py-3.5"><p className="font-semibold text-slate-800">{[lead.firstName, lead.lastName].filter(Boolean).join(" ") || "Unnamed lead"}</p><p className="mt-0.5 text-xs text-slate-400">{lead.leadNumber} · {lead.sourceName}</p></td><td className="px-3 py-3.5 text-xs font-semibold text-slate-600">{humanize(lead.stage)}</td><td className="px-3 py-3.5 text-slate-600">{lead.ownerName}</td><td className="px-3 py-3.5 font-semibold text-slate-800">{lead.ageDays}d</td><td className={`px-3 py-3.5 ${lead.inactiveDays >= report.inactiveThresholdDays ? "font-semibold text-rose-600" : "text-slate-500"}`}>{lead.inactiveDays}d</td><td className="px-5 py-3.5 text-right"><Link to={`/leads?search=${encodeURIComponent(lead.leadNumber)}`} className="text-xs font-semibold text-brand-700 hover:text-brand-900">Review</Link></td></tr>)}</tbody></table></div> : <div className="px-5 py-10 text-center text-sm text-slate-400">No open leads.</div>}</section></section>
    <Definition>Age is measured from lead creation to now. Inactivity is measured from the most recent lead update. Pipeline value is the sum of estimated value on open leads. This report always shows the current pipeline and does not use the historical date selector.</Definition>
  </>;
}

function TrendsReport({ report }) {
  const money = new Intl.NumberFormat("en-CA", { style: "currency", currency: report.currency || "CAD", maximumFractionDigits: 0 });
  const maximum = Math.max(...report.trend.flatMap((item) => [item.received, item.converted, item.lost]), 1);
  const formatPeriod = (value) => new Intl.DateTimeFormat("en-CA", { year: "numeric", month: "short", day: report.range.granularity === "day" ? "numeric" : undefined, timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`));
  return <>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SummaryCard icon={ContactRound} label="Received" value={report.summary.received} /><SummaryCard icon={CheckCircle2} label="Converted" value={`${report.summary.converted} · ${report.summary.conversionRate}%`} tone="emerald" /><SummaryCard icon={Timer} label="Average conversion time" value={`${report.summary.averageConversionDays ?? 0} days`} /><SummaryCard icon={WalletCards} label="Converted value" value={money.format(report.summary.convertedValue)} tone="violet" /></section>
    <section className="overflow-hidden rounded-3xl border border-white/80 bg-white shadow-[0_18px_55px_rgba(28,45,74,0.08)]"><div className="border-b border-slate-200/70 px-5 py-4"><h2 className="text-base font-semibold text-slate-950">Conversion trend</h2><p className="mt-1 text-xs text-slate-500">Events grouped by {report.range.granularity}; each event is counted when it happened.</p></div>{report.trend.length ? <div className="divide-y divide-slate-100">{report.trend.map((item) => <div key={item.period} className="grid gap-4 px-5 py-4 md:grid-cols-[130px_minmax(280px,1fr)_240px] md:items-center"><p className="text-sm font-semibold text-slate-700">{formatPeriod(item.period)}</p><div className="space-y-2"><div className="flex items-center gap-3"><span className="w-16 text-[10px] font-semibold uppercase tracking-wide text-slate-400">Received</span><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-500" style={{ width: `${(item.received / maximum) * 100}%` }} /></div><span className="w-8 text-right text-xs font-semibold text-slate-700">{item.received}</span></div><div className="flex items-center gap-3"><span className="w-16 text-[10px] font-semibold uppercase tracking-wide text-slate-400">Converted</span><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${(item.converted / maximum) * 100}%` }} /></div><span className="w-8 text-right text-xs font-semibold text-emerald-700">{item.converted}</span></div><div className="flex items-center gap-3"><span className="w-16 text-[10px] font-semibold uppercase tracking-wide text-slate-400">Lost</span><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-rose-400" style={{ width: `${(item.lost / maximum) * 100}%` }} /></div><span className="w-8 text-right text-xs font-semibold text-rose-600">{item.lost}</span></div></div><div className="md:text-right"><p className="text-sm font-semibold text-slate-800">{money.format(item.convertedValue)}</p><p className="mt-0.5 text-xs text-slate-400">converted value</p></div></div>)}</div> : <div className="px-6 py-16 text-center text-sm text-slate-400">No lead events in this period.</div>}</section>
    <Definition>Received is grouped by lead creation time, converted by conversion time, and lost by lost time. Actual conversion value is attributed to the conversion period. Average conversion time measures creation to conversion.</Definition>
  </>;
}

function WorkloadReport({ report }) {
  const money = new Intl.NumberFormat("en-CA", { style: "currency", currency: report.currency || "CAD", maximumFractionDigits: 0 });
  return <>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SummaryCard icon={UsersRound} label="Employees" value={report.summary.employees} /><SummaryCard icon={ContactRound} label="Open leads" value={report.summary.openLeads} /><SummaryCard icon={AlertTriangle} label="Overdue lead actions" value={report.summary.overdueActions} tone="violet" /><SummaryCard icon={WalletCards} label="Pipeline assigned" value={money.format(report.summary.pipelineValue)} tone="emerald" /></section>
    <section className="overflow-hidden rounded-3xl border border-white/80 bg-white shadow-[0_18px_55px_rgba(28,45,74,0.08)]"><div className="border-b border-slate-200/70 px-5 py-4"><h2 className="text-base font-semibold text-slate-950">Workload distribution</h2><p className="mt-1 text-xs text-slate-500">Current open lead responsibility and upcoming work by employee.</p></div>{report.employees.length ? <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead><tr className="border-b border-slate-200 bg-slate-50/70 text-[10px] font-semibold uppercase tracking-[0.07em] text-slate-500"><th className="px-5 py-3">Employee</th><th className="px-4 py-3">Open leads</th><th className="px-4 py-3">Lead actions</th><th className="px-4 py-3">Follow-ups</th><th className="px-4 py-3">Consultations</th><th className="px-4 py-3">Ready to convert</th><th className="px-5 py-3">Pipeline value</th></tr></thead><tbody>{report.employees.map((employee) => <tr key={employee.id} className="border-b border-slate-100 align-top text-sm last:border-0"><td className="px-5 py-4"><p className="font-semibold text-slate-900">{employee.name}</p><p className="mt-0.5 text-xs text-slate-400">{employee.email}</p></td><td className="px-4 py-4 text-lg font-semibold text-slate-800">{employee.openLeads}</td><td className="px-4 py-4"><p className="text-slate-700">{employee.actionsToday} due today</p><p className={`mt-1 text-xs ${employee.overdueActions ? "font-semibold text-rose-600" : "text-slate-400"}`}>{employee.overdueActions} overdue</p></td><td className="px-4 py-4"><p className="text-slate-700">{employee.pendingFollowUps} pending</p><p className={`mt-1 text-xs ${employee.overdueFollowUps ? "font-semibold text-rose-600" : "text-slate-400"}`}>{employee.overdueFollowUps} overdue</p></td><td className="px-4 py-4"><p className="inline-flex items-center gap-1.5 text-slate-700"><CalendarClock className="h-3.5 w-3.5 text-slate-400" />{employee.upcomingConsultations} next 7 days</p></td><td className="px-4 py-4 font-semibold text-emerald-700">{employee.readyToConvert}</td><td className="px-5 py-4 font-semibold text-slate-800">{money.format(employee.pipelineValue)}</td></tr>)}</tbody></table></div> : <div className="px-6 py-16 text-center text-sm text-slate-400">No active employees available.</div>}</section>
    <Definition>Workload uses the current open pipeline. Lead actions come from each lead’s next action; follow-ups and consultations use their assigned employee. Upcoming consultations cover the next seven days.</Definition>
  </>;
}

function Definition({ children }) {
  return <section className="rounded-2xl border border-slate-200/70 bg-slate-50 px-5 py-4"><h2 className="text-sm font-semibold text-slate-800">How this report is calculated</h2><p className="mt-2 text-xs leading-5 text-slate-500">{children} Duplicate and archived records are excluded. Consultants see assigned leads; administrators see the agency report.</p></section>;
}

export default function LeadReportsPage() {
  const [view, setView] = useState("funnel");
  const [days, setDays] = useState("30");
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const requestSequence = useRef(0);

  const loadReport = useCallback(async () => {
    const sequence = ++requestSequence.current;
    try {
      setLoading(true);
      setReport(null);
      const endpoint = { funnel: "funnel", sources: "sources", employees: "employees", lost: "lost", response: "response-time", ageing: "ageing", trends: "trends", workload: "workload" }[view] || "funnel";
      const response = await api.get(`/leads/reports/${endpoint}?days=${days}`);
      if (sequence !== requestSequence.current) return;
      setReport(response.data.data);
      setError("");
    } catch (requestError) {
      if (sequence !== requestSequence.current) return;
      setReport(null);
      setError(requestError.response?.data?.message || `The ${view} report could not be loaded.`);
    } finally {
      if (sequence === requestSequence.current) setLoading(false);
    }
  }, [days, view]);

  useEffect(() => { loadReport(); }, [loadReport]);

  return <section className="space-y-6 pb-8">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-brand-600">Lead intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.03em] text-slate-950">Lead reports</h1><p className="mt-1.5 text-sm text-slate-500">Understand funnel movement and the sources creating real clients.</p></div><div className="flex items-center gap-2">{!["ageing", "workload"].includes(view) ? <select value={days} onChange={(event) => setDays(event.target.value)} className="h-10 rounded-full border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-700 outline-none focus:border-brand-300 focus:ring-4 focus:ring-brand-100">{ranges.map((range) => <option key={range.value} value={range.value}>{range.label}</option>)}</select> : <span className="inline-flex h-10 items-center rounded-full bg-slate-100 px-4 text-sm font-semibold text-slate-600">Current pipeline</span>}<Link to="/lead-dashboard" className="inline-flex h-10 items-center gap-2 rounded-full border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-700 hover:bg-slate-50">Dashboard<ArrowRight className="h-4 w-4" /></Link></div></header>
    <nav className="inline-flex max-w-full overflow-x-auto rounded-full bg-slate-100 p-1" aria-label="Lead reports">{[["funnel", "Funnel"], ["sources", "Sources"], ["employees", "Employees"], ["lost", "Lost leads"], ["response", "Response time"], ["ageing", "Ageing"], ["trends", "Trends"], ["workload", "Workload"]].map(([id, label]) => <button key={id} type="button" onClick={() => setView(id)} className={`h-9 shrink-0 rounded-full px-4 text-sm font-semibold transition ${view === id ? "bg-white text-slate-900 shadow-sm" : "text-slate-500"}`}>{label}</button>)}</nav>
    {error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 px-5 py-4 text-sm text-rose-700"><p>{error}</p><button type="button" onClick={loadReport} className="mt-2 font-semibold">Try again</button></div> : null}
    {loading ? <ReportSkeleton /> : report && (view === "sources" ? Array.isArray(report.sources) : view === "employees" ? Array.isArray(report.employees) : view === "lost" ? Array.isArray(report.reasons) : view === "response" ? Array.isArray(report.employees) && Array.isArray(report.sources) : view === "ageing" ? Array.isArray(report.buckets) : view === "trends" ? Array.isArray(report.trend) : view === "workload" ? Array.isArray(report.employees) : Array.isArray(report.funnel)) ? <div className="space-y-5">{view === "sources" ? <SourceReport report={report} /> : view === "employees" ? <EmployeeReport report={report} /> : view === "lost" ? <LostReport report={report} /> : view === "response" ? <ResponseTimeReport report={report} /> : view === "ageing" ? <AgeingReport report={report} /> : view === "trends" ? <TrendsReport report={report} /> : view === "workload" ? <WorkloadReport report={report} /> : <FunnelReport report={report} />}</div> : null}
  </section>;
}
