const QUESTIONS = Object.freeze({
  "Full legal name": "What is your full legal name?",
  "Date of birth": "What is your date of birth?",
  Citizenship: "What is your country of citizenship?",
  "Current country of residence": "Which country do you currently live in?",
  "Currently in Canada?": "Are you currently in Canada?",
  "First entry into Canada": "When did you first enter Canada?",
  "Most recent entry into Canada": "When did you most recently enter Canada?",
  "Current immigration status": "What is your current immigration status?",
  "Other status": "How would you describe your current immigration status?",
  "Status approval / issue date": "When was your status or permit approved or issued?",
  "Permit/status approval or issue date": "When was your status or permit approved or issued?",
  "Status expiry date": "When does your status or permit expire?",
  "Permit/status expiry date": "When does your status or permit expire?",
  "Pending IRCC application?": "Do you currently have an application pending with IRCC?",
  "Application type": "What type of application is it?",
  "Submitted date": "When was the application submitted?",
  "Current application status": "What is the current status of the application?",
  "Studied in Canada?": "Have you studied in Canada?",
  Institution: "Which institution did you attend?",
  Program: "What program did you study?",
  Province: "Which province did you study in?",
  "Program start date": "When did your program start?",
  "Completion / expected completion": "When did you complete, or expect to complete, your program?",
  "Program completed?": "Did you complete the program?",
  "Study permit approval date": "When was your study permit approved?",
  "Study permit expiry date": "When does your study permit expire?",
  "Current study status": "What is your current study status?",
  "Currently working in Canada?": "Are you currently working in Canada?",
  Employer: "Who is your employer?",
  "Job title": "What is your job title?",
  "Employment start date": "When did you start this job?",
  "Employment type": "What type of employment is it?",
  "Hours per week": "How many hours do you work each week?",
  "NOC code": "What is your NOC code, if you know it?",
  "NOC code, if known": "What is your NOC code, if you know it?",
  "Work permit type": "What type of work permit do you have?",
  "Work permit approval date": "When was your work permit approved?",
  "Work permit expiry date": "When does your work permit expire?",
  "Total Canadian work experience": "How much Canadian work experience do you have?",
  "Work experience outside Canada?": "Do you have work experience outside Canada?",
  "Foreign country": "Which country did you work in?",
  Country: "Which country did you work in?",
  "Foreign employer": "Who was your employer outside Canada?",
  "Foreign job title": "What was your job title outside Canada?",
  From: "When did this job start?",
  To: "When did this job end?",
  "Previously applied to IRCC?": "Have you previously applied to IRCC?",
  "Application date": "When did you apply?",
  Outcome: "What was the outcome?",
  "Any visa, permit, or immigration refusal?": "Have you ever had a visa, permit, or immigration application refused?",
  "Refusal date": "When was the application refused?",
  "Reason for refusal": "Why was the application refused, if you know?",
  "Reason for refusal, if known": "Why was the application refused, if you know?",
  "Marital status": "What is your marital status?",
  "Number of dependant children": "How many dependant children do you have?",
  "Spouse / partner in Canada?": "Is your spouse or partner in Canada?",
  "Spouse / partner status": "What is your spouse or partner's immigration status?",
  "Spouse/partner immigration status": "What is your spouse or partner's immigration status?",
  "Family part of this consultation?": "Is your spouse or family part of what you want help with?",
  "Completed a language test?": "Have you completed a language test?",
  "Language test": "Which language test did you complete?",
  Test: "Which language test did you complete?",
  "Test date": "When did you take the test?",
  Listening: "What was your listening score?",
  Reading: "What was your reading score?",
  Writing: "What was your writing score?",
  Speaking: "What was your speaking score?",
  "Completed an ECA?": "Have you completed an ECA for education outside Canada?",
  "ECA organization": "Which organization completed your ECA?",
  "ECA completion date": "When was your ECA completed?",
  "Immigration deadline?": "Do you have an immigration deadline we should know about?",
  "Deadline type": "What type of deadline is it?",
  "Deadline date": "When is the deadline?",
  "Deadline details": "What should we know about this deadline?",
  "Active refusal, removal, loss of status, or another urgent issue?": "Do you have a refusal, removal order, loss of status, or another urgent immigration issue?",
  "Urgent issue details": "Please tell us what is happening.",
  "Anything else the consultant should know?": "Is there anything else the consultant should know?",
});

export function preConsultationQuestion(label) {
  return QUESTIONS[label] || label;
}
