// FIRST-DRAFT SEED DATA — not authoritative immigration-law scoping.
// This is Phase 1's job: prove the *mechanism* (case type -> per-section
// requirement level) works end to end against real data. The actual
// required/optional/not_applicable calls per case type below need review
// by someone who owns the immigration-practice side before Phase 5 (UI)
// or Phase 6 (client-facing questionnaire gating) ship against them.
//
// Levels: "required" | "optional" | "not_applicable".
// Any section key omitted for a case type defaults to "optional" (see
// caseRequirementResolver.js) — never "not_applicable" by omission, so a
// forgotten mapping never silently hides a section a consultant might need.

const REQUIRED = "required";
const OPTIONAL = "optional";
const NOT_APPLICABLE = "not_applicable";

export const CASE_TYPE_REQUIREMENTS = {
  "canadian citizenship": {
    applicantDetails: REQUIRED,
    spouseDetails: OPTIONAL,
    children: OPTIONAL,
    siblingDetails: NOT_APPLICABLE,
    parentDetails: NOT_APPLICABLE,
    activityHistory: REQUIRED,
    addressHistory: REQUIRED,
    travelHistory: REQUIRED,
    identityPermits: REQUIRED,
    canadianStatus: REQUIRED,
    backgroundAdmissibility: REQUIRED,
    relationshipSponsorship: NOT_APPLICABLE,
    programDetails: NOT_APPLICABLE,
    humanitarianCitizenship: REQUIRED,
    rehabilitation: OPTIONAL,
    refugeeProtection: NOT_APPLICABLE,
  },
  "general consultation": {
    applicantDetails: REQUIRED,
    spouseDetails: OPTIONAL,
    children: OPTIONAL,
    siblingDetails: NOT_APPLICABLE,
    parentDetails: NOT_APPLICABLE,
    activityHistory: OPTIONAL,
    addressHistory: OPTIONAL,
    travelHistory: OPTIONAL,
    identityPermits: OPTIONAL,
    canadianStatus: OPTIONAL,
    backgroundAdmissibility: OPTIONAL,
    relationshipSponsorship: NOT_APPLICABLE,
    programDetails: OPTIONAL,
    humanitarianCitizenship: NOT_APPLICABLE,
    rehabilitation: NOT_APPLICABLE,
    refugeeProtection: NOT_APPLICABLE,
  },
  "lmia - employer service": {
    applicantDetails: OPTIONAL,
    spouseDetails: NOT_APPLICABLE,
    children: NOT_APPLICABLE,
    siblingDetails: NOT_APPLICABLE,
    parentDetails: NOT_APPLICABLE,
    activityHistory: NOT_APPLICABLE,
    addressHistory: NOT_APPLICABLE,
    travelHistory: NOT_APPLICABLE,
    identityPermits: NOT_APPLICABLE,
    canadianStatus: NOT_APPLICABLE,
    backgroundAdmissibility: NOT_APPLICABLE,
    relationshipSponsorship: NOT_APPLICABLE,
    programDetails: REQUIRED,
    humanitarianCitizenship: NOT_APPLICABLE,
    rehabilitation: NOT_APPLICABLE,
    refugeeProtection: NOT_APPLICABLE,
  },
  "pr - express entry - pnp": {
    applicantDetails: REQUIRED,
    spouseDetails: REQUIRED,
    children: REQUIRED,
    siblingDetails: OPTIONAL,
    parentDetails: OPTIONAL,
    activityHistory: REQUIRED,
    addressHistory: REQUIRED,
    travelHistory: REQUIRED,
    identityPermits: REQUIRED,
    canadianStatus: REQUIRED,
    backgroundAdmissibility: REQUIRED,
    relationshipSponsorship: NOT_APPLICABLE,
    programDetails: REQUIRED,
    humanitarianCitizenship: OPTIONAL,
    rehabilitation: OPTIONAL,
    refugeeProtection: NOT_APPLICABLE,
  },
  "spousal and family sponsorship": {
    applicantDetails: REQUIRED,
    spouseDetails: REQUIRED,
    children: REQUIRED,
    siblingDetails: OPTIONAL,
    parentDetails: OPTIONAL,
    activityHistory: REQUIRED,
    addressHistory: REQUIRED,
    travelHistory: REQUIRED,
    identityPermits: REQUIRED,
    canadianStatus: REQUIRED,
    backgroundAdmissibility: REQUIRED,
    relationshipSponsorship: REQUIRED,
    programDetails: OPTIONAL,
    humanitarianCitizenship: NOT_APPLICABLE,
    rehabilitation: OPTIONAL,
    refugeeProtection: NOT_APPLICABLE,
  },
  "study permit": {
    applicantDetails: REQUIRED,
    spouseDetails: OPTIONAL,
    children: OPTIONAL,
    siblingDetails: NOT_APPLICABLE,
    parentDetails: NOT_APPLICABLE,
    activityHistory: REQUIRED,
    addressHistory: REQUIRED,
    travelHistory: REQUIRED,
    identityPermits: REQUIRED,
    canadianStatus: REQUIRED,
    backgroundAdmissibility: REQUIRED,
    relationshipSponsorship: NOT_APPLICABLE,
    programDetails: REQUIRED,
    humanitarianCitizenship: NOT_APPLICABLE,
    rehabilitation: OPTIONAL,
    refugeeProtection: NOT_APPLICABLE,
  },
  "visitor visa - trv": {
    applicantDetails: REQUIRED,
    spouseDetails: OPTIONAL,
    children: OPTIONAL,
    siblingDetails: NOT_APPLICABLE,
    parentDetails: NOT_APPLICABLE,
    activityHistory: REQUIRED,
    addressHistory: REQUIRED,
    travelHistory: REQUIRED,
    identityPermits: REQUIRED,
    canadianStatus: REQUIRED,
    backgroundAdmissibility: REQUIRED,
    relationshipSponsorship: NOT_APPLICABLE,
    programDetails: REQUIRED,
    humanitarianCitizenship: NOT_APPLICABLE,
    rehabilitation: OPTIONAL,
    refugeeProtection: NOT_APPLICABLE,
  },
  "work permit / open work permit": {
    applicantDetails: REQUIRED,
    spouseDetails: OPTIONAL,
    children: OPTIONAL,
    siblingDetails: NOT_APPLICABLE,
    parentDetails: NOT_APPLICABLE,
    activityHistory: REQUIRED,
    addressHistory: REQUIRED,
    travelHistory: REQUIRED,
    identityPermits: REQUIRED,
    canadianStatus: REQUIRED,
    backgroundAdmissibility: REQUIRED,
    relationshipSponsorship: NOT_APPLICABLE,
    programDetails: REQUIRED,
    humanitarianCitizenship: NOT_APPLICABLE,
    rehabilitation: OPTIONAL,
    refugeeProtection: NOT_APPLICABLE,
  },
};

export const REQUIREMENT_LEVELS = { REQUIRED, OPTIONAL, NOT_APPLICABLE };
